### ISSUE TITLE
Tests from semver

### ISSUE THREAD

**Issue by Eh2406** [pubgrub-rs/semver-pubgrub#1]

**Comment by Eh2406** [comment]
Also bring in test from https://github.com/dtolnay/semver/blob/master/tests/test_version_req.rs

**Comment by Eh2406** [comment]
Test are copied over https://github.com/pubgrub-rs/semver-pubgrub/commit/3b608efe739fbf8248872b3089c9ac92e1bc32b2
Still working on other forms of testing.

**Comment by dtolnay** [comment]
It would be good to indicate the license of the contents of tests/test_version_req.rs somewhere, because it is not MPL 2.0.

**Comment by Eh2406** [comment]
Good call and sorry.

**Comment by Eh2406** [comment]
I added clarification to the top of that file and the readme.
Is that adequate/reasonable?

**Comment by dtolnay** [comment]
_The original is licensed "MIT OR Apache-2.0"_ &mdash; this is not the relevant thing. The relevant thing is what is the license of that code in that file in *your* repo. People need to know what terms they need to comply with when redistributing the contents of semver-pubgrub repo, and separately, how they are required to license any contributions that they make to this repo, or "derivative works".

Separately, be aware that both the MIT license and Apache 2.0 license puts the onus on you to supply a copy of the license text. At least by my interpretation, this seems pretty unambiguous in both licenses. MIT: _"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."_ Apache: _"You must give any other recipients of the Work or Derivative Works a copy of this License"_

I recommend reading through the entire license text to see if there is anything else you might have missed.

**Comment by Eh2406** [comment]
Having taken the time to think about it, thank you for pointing out how this will confuse contributors. I think if I add the MIT and Apache-2.0 files, and an explanation to the relevant tests it will still be confusing to contributors. (Users are not affected. As `semver` is a dependency of this library. So users will need to obtain and abide by your licenses independently of what I do in my tests.) So I have removed the test file, not just from the working tree but from the history as well.
